# Service resource for the weather app. Exposes the pod on selected port.
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weather-chart.fullname" . }}
  labels:
    {{- include "weather-chart.labels" . | nindent 4 }}
spec:
  # Service type (ClusterIP/NodePort/LoadBalancer)
  type: {{ .Values.service.type }}
  # Ports exposed by the Service and the target container port
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  # Selector selects pods that this Service routes to
  selector:
    {{- include "weather-chart.selectorLabels" . | nindent 4 }}